# Generated by Django 5.0.4 on 2026-08-07 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('couples', '0002_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Relationship Pact', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacts', to='couples.couple')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('live', 'Live'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('proposed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='pacts.pactversion')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pact_versions', to='couples.couple')),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pacts.pact')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_pact_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PactSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pacts.pactversion')),
            ],
        ),
        migrations.CreateModel(
            name='PactClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_proposed_clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pact_clauses', to='analysis.proposedclause')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='pacts.pactsection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='pacts.pactversion')),
            ],
        ),
        migrations.AddField(
            model_name='pact',
            name='live_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_for_pact', to='pacts.pactversion'),
        ),
        migrations.CreateModel(
            name='ClauseProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clause_proposals', to=settings.AUTH_USER_MODEL)),
                ('source_proposed_clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clause_proposals', to='analysis.proposedclause')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_proposals', to='pacts.pactversion')),
            ],
        ),
        migrations.CreateModel(
            name='ClauseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('proposal_revision', models.PositiveSmallIntegerField()),
                ('approved_at', models.DateTimeField()),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_approvals', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_approvals', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pacts.clauseproposal')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_approvals', to='pacts.pactversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='pactversion',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='pacts_pactv_couple__a85f60_idx'),
        ),
        migrations.AddIndex(
            model_name='pactversion',
            index=models.Index(fields=['pact', 'status'], name='pacts_pactv_pact_id_11ccfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pactversion',
            constraint=models.UniqueConstraint(fields=('pact', 'version'), name='unique_pact_version_number'),
        ),
        migrations.AddIndex(
            model_name='pactsection',
            index=models.Index(fields=['version', 'sort_order'], name='pacts_pacts_version_eaffdc_idx'),
        ),
        migrations.AddIndex(
            model_name='pactclause',
            index=models.Index(fields=['version', 'sort_order'], name='pacts_pactc_version_bafc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='pact',
            index=models.Index(fields=['couple', 'created_at'], name='pacts_pact_couple__04e1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='clauseproposal',
            index=models.Index(fields=['version', 'created_at'], name='pacts_claus_version_8a42cc_idx'),
        ),
        migrations.AddIndex(
            model_name='clauseproposal',
            index=models.Index(fields=['revision'], name='pacts_claus_revisio_7ffd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='clauseapproval',
            index=models.Index(fields=['version', 'invalidated_at'], name='pacts_claus_version_f6aeee_idx'),
        ),
        migrations.AddIndex(
            model_name='clauseapproval',
            index=models.Index(fields=['proposal', 'invalidated_at'], name='pacts_claus_proposa_3d6f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='clauseapproval',
            index=models.Index(fields=['user', 'created_at'], name='pacts_claus_user_id_3cce6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='clauseapproval',
            constraint=models.UniqueConstraint(fields=('proposal', 'user', 'proposal_revision'), name='unique_clause_approval_per_revision'),
        ),
    ]
