# Generated by Django 5.0.4 on 2026-08-07 20:16

import apps.pacts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_entitlement'),
        ('pacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PactDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.pacts.models.pact_document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField()),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pact_documents', to='couples.couple')),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pacts.pact')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='pacts.pactversion')),
            ],
        ),
        migrations.CreateModel(
            name='PactDocumentDownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pact_document_tokens', to='couples.couple')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='pacts.pactdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pact_document_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pactdocument',
            index=models.Index(fields=['couple', 'generated_at'], name='pacts_pactd_couple__8047d8_idx'),
        ),
        migrations.AddIndex(
            model_name='pactdocument',
            index=models.Index(fields=['checksum_sha256'], name='pacts_pactd_checksu_15cfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='pactdocumentdownloadtoken',
            index=models.Index(fields=['user', 'expires_at'], name='pacts_pactd_user_id_08d165_idx'),
        ),
        migrations.AddIndex(
            model_name='pactdocumentdownloadtoken',
            index=models.Index(fields=['document', 'created_at'], name='pacts_pactd_documen_7ef357_idx'),
        ),
    ]
