# Generated by Django 5.0.4 on 2026-08-07 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_entitlement'),
        ('topics', '0003_coupletopic_customquestion_customquestionoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_kind', models.CharField(choices=[('built_in', 'Built-in'), ('custom', 'Custom')], max_length=20)),
                ('topic_stable_key', models.CharField(max_length=160)),
                ('topic_version', models.PositiveSmallIntegerField()),
                ('expected_question_count', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('built_in_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='topics.topic')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_sessions', to='couples.couple')),
                ('custom_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='topics.coupletopic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_stable_key', models.CharField(max_length=160)),
                ('question_version', models.PositiveSmallIntegerField()),
                ('selected_option_key', models.CharField(blank=True, max_length=160)),
                ('text_answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('built_in_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='topics.question')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_responses', to='couples.couple')),
                ('custom_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='topics.customquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_responses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='responses.topicsession')),
            ],
        ),
        migrations.CreateModel(
            name='TopicMemberCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_completions', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_completions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='responses.topicsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='topicsession',
            index=models.Index(fields=['couple', 'topic_kind'], name='responses_t_couple__8b7db3_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsession',
            index=models.Index(fields=['topic_stable_key', 'topic_version'], name='responses_t_topic_s_f37928_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicsession',
            constraint=models.UniqueConstraint(fields=('couple', 'topic_kind', 'topic_stable_key', 'topic_version'), name='unique_topic_session_per_couple_topic_version'),
        ),
        migrations.AddIndex(
            model_name='topicresponse',
            index=models.Index(fields=['session', 'user'], name='responses_t_session_41d98c_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresponse',
            index=models.Index(fields=['couple', 'user'], name='responses_t_couple__395f22_idx'),
        ),
        migrations.AddIndex(
            model_name='topicresponse',
            index=models.Index(fields=['question_stable_key', 'question_version'], name='responses_t_questio_0fb4f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicresponse',
            constraint=models.UniqueConstraint(fields=('session', 'user', 'question_stable_key', 'question_version'), name='unique_response_per_user_question_version'),
        ),
        migrations.AddIndex(
            model_name='topicmembercompletion',
            index=models.Index(fields=['session', 'completed_at'], name='responses_t_session_c82946_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmembercompletion',
            index=models.Index(fields=['couple', 'user'], name='responses_t_couple__ae593a_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicmembercompletion',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_topic_completion_per_member'),
        ),
    ]
