# Generated by Django 5.0.4 on 2026-08-07 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_entitlement'),
        ('responses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_analysis_jobs', to='couples.couple')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='responses.topicsession')),
                ('triggered_by_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_analysis_jobs', to='responses.topicmembercompletion')),
            ],
            options={
                'indexes': [models.Index(fields=['couple', 'status', 'queued_at'], name='responses_t_couple__cbf302_idx'), models.Index(fields=['status', 'queued_at'], name='responses_t_status_3aa0c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicSyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('partner_completed_waiting', 'Partner completed, waiting for you'), ('analysis_queued', 'Analysis queued'), ('analysis_ready', 'Analysis ready')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_sync_events', to='couples.couple')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='responses.topicsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'event_type'], name='responses_t_session_7403f0_idx'), models.Index(fields=['user', 'created_at'], name='responses_t_user_id_8318c1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='topicsyncevent',
            constraint=models.UniqueConstraint(fields=('session', 'user', 'event_type'), name='unique_topic_sync_event_per_user_type'),
        ),
    ]
