# Generated by Django 5.0.4 on 2026-08-07 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('email_verification', 'Email verification')], max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'created_at'], name='accounts_em_email_c46531_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_2be763_idx'), models.Index(fields=['consumed_at'], name='accounts_em_consume_90a8a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_hash', models.CharField(max_length=128, unique=True)),
                ('refresh_token_hash', models.CharField(max_length=128, unique=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_307579_idx'), models.Index(fields=['access_expires_at'], name='accounts_au_access__4d7729_idx'), models.Index(fields=['refresh_expires_at'], name='accounts_au_refresh_da22dc_idx'), models.Index(fields=['revoked_at'], name='accounts_au_revoked_bae3d3_idx')],
            },
        ),
    ]
