# Generated by Django 5.0.4 on 2026-08-07 18:17

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_authsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('pronouns', models.CharField(blank=True, max_length=80)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.accounts.models.user_avatar_upload_path)),
                ('preferred_language', models.CharField(default='en', max_length=12)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
