# Generated by Django 5.0.4 on 2026-08-07 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0005_seed_follow_up_prompt'),
        ('couples', '0002_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('individual', 'Individual'), ('couple', 'Couple'), ('conflict', 'Conflict')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived')], default='open', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_conversations', to='couples.couple')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_coach_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('render_as', models.CharField(default='text', max_length=20)),
                ('explicitly_shared_with_partner', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='coach.coachconversation')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_messages', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='CoachParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('partner', 'Partner')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='coach.coachconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Refused'), ('failed', 'Failed'), ('invalid_output', 'Invalid output'), ('safety_blocked', 'Safety blocked')], max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('context_message_ids', models.JSONField(blank=True, default=list)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('refusal_reason', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='coach.coachconversation')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_runs', to='couples.couple')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coach_runs', to='ai.aipromptversion')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_runs', to=settings.AUTH_USER_MODEL)),
                ('response_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_runs', to='coach.coachmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='coachconversation',
            index=models.Index(fields=['owner', 'scope', 'status', 'created_at'], name='coach_coach_owner_i_38c321_idx'),
        ),
        migrations.AddIndex(
            model_name='coachconversation',
            index=models.Index(fields=['couple', 'scope', 'status', 'created_at'], name='coach_coach_couple__4da041_idx'),
        ),
        migrations.AddIndex(
            model_name='coachmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='coach_coach_convers_29dfca_idx'),
        ),
        migrations.AddIndex(
            model_name='coachmessage',
            index=models.Index(fields=['author', 'explicitly_shared_with_partner'], name='coach_coach_author__80b19b_idx'),
        ),
        migrations.AddIndex(
            model_name='coachmessage',
            index=models.Index(fields=['couple', 'created_at'], name='coach_coach_couple__a57fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='coachparticipant',
            index=models.Index(fields=['user', 'conversation'], name='coach_coach_user_id_cee5cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_coach_participant_per_conversation_user'),
        ),
        migrations.AddIndex(
            model_name='coachrun',
            index=models.Index(fields=['conversation', 'created_at'], name='coach_coach_convers_02b5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='coachrun',
            index=models.Index(fields=['status', 'created_at'], name='coach_coach_status_9c785a_idx'),
        ),
    ]
