# Generated by Django 5.0.4 on 2026-08-07 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('archived', 'Archived'), ('dissolved', 'Dissolved')], default='pending', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('dissolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_couples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoupleMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('partner_1', 'Partner 1'), ('partner_2', 'Partner 2')], max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('left', 'Left'), ('removed', 'Removed')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_partner_invitations', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='couples.couple')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_partner_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['status', 'created_at'], name='couples_cou_status_ebdb21_idx'),
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['created_by', 'created_at'], name='couples_cou_created_683a06_idx'),
        ),
        migrations.AddIndex(
            model_name='couplemember',
            index=models.Index(fields=['couple', 'status'], name='couples_cou_couple__56e531_idx'),
        ),
        migrations.AddIndex(
            model_name='couplemember',
            index=models.Index(fields=['user', 'status'], name='couples_cou_user_id_c0d1c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='couplemember',
            constraint=models.UniqueConstraint(fields=('couple', 'user'), name='unique_member_per_couple'),
        ),
        migrations.AddConstraint(
            model_name='couplemember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('couple', 'role'), name='unique_active_role_per_couple'),
        ),
        migrations.AddConstraint(
            model_name='couplemember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_couple_per_user'),
        ),
        migrations.AddIndex(
            model_name='partnerinvitation',
            index=models.Index(fields=['couple', 'created_at'], name='couples_par_couple__97d76c_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvitation',
            index=models.Index(fields=['email', 'created_at'], name='couples_par_email_30cf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvitation',
            index=models.Index(fields=['expires_at'], name='couples_par_expires_55bee7_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvitation',
            index=models.Index(fields=['accepted_at'], name='couples_par_accepte_ba480c_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvitation',
            index=models.Index(fields=['revoked_at'], name='couples_par_revoked_09e375_idx'),
        ),
    ]
