# Generated by Django 5.0.4 on 2026-08-07 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('apple_iap', 'Apple In-App Purchase'), ('google_iap', 'Google In-App Purchase')], default='manual', max_length=32)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='couples.couple')),
            ],
            options={
                'indexes': [models.Index(fields=['couple', 'starts_at'], name='couples_ent_couple__4bca20_idx'), models.Index(fields=['expires_at'], name='couples_ent_expires_322b65_idx'), models.Index(fields=['revoked_at'], name='couples_ent_revoked_fc94ab_idx')],
            },
        ),
    ]
