# Generated by Django 5.0.4 on 2026-08-07 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=20)),
                ('product_id', models.CharField(max_length=255)),
                ('original_transaction_id', models.CharField(max_length=255)),
                ('latest_transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('revoked', 'Revoked')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('raw_latest_event', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='couples.couple')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=20)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='IAPPurchaseAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=20)),
                ('app_account_token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iap_accounts', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iap_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'platform'], name='billing_iap_user_id_9be47b_idx'), models.Index(fields=['couple', 'platform'], name='billing_iap_couple__1b7af9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='iappurchaseaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'app_account_token'), name='unique_iap_platform_app_account_token'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['couple', 'status'], name='billing_sub_couple__4cca70_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'status'], name='billing_sub_owner_i_0be096_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='billing_sub_expires_b7e94d_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('platform', 'original_transaction_id'), name='unique_iap_original_transaction'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['platform', 'event_type'], name='billing_sub_platfor_f0ce4c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['status', 'created_at'], name='billing_sub_status_e4d5e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionevent',
            constraint=models.UniqueConstraint(fields=('platform', 'event_id'), name='unique_iap_platform_event'),
        ),
    ]
