# Generated by Django 5.0.4 on 2026-08-07 21:19

import apps.moments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_entitlement'),
        ('topics', '0003_coupletopic_customquestion_customquestionoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='couples.couple')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_moments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MomentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image')], default='image', max_length=20)),
                ('file', models.ImageField(upload_to=apps.moments.models.moment_media_upload_path)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.moments.models.moment_thumbnail_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('thumbnail_width', models.PositiveIntegerField(default=0)),
                ('thumbnail_height', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('metadata_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_media', to='couples.couple')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='moments.moment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_moment_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MomentMediaDownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('variant', models.CharField(default='original', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_media_tokens', to='couples.couple')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='moments.momentmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_media_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MomentTopicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_topic_links', to='couples.couple')),
                ('custom_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moment_links', to='topics.coupletopic')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='moments.moment')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moment_links', to='topics.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='moments_mom_couple__a0fc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['occurred_on', 'created_at'], name='moments_mom_occurre_662d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='momentmedia',
            index=models.Index(fields=['moment', 'created_at'], name='moments_mom_moment__cef5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='momentmedia',
            index=models.Index(fields=['couple', 'created_at'], name='moments_mom_couple__4e048f_idx'),
        ),
        migrations.AddIndex(
            model_name='momentmediadownloadtoken',
            index=models.Index(fields=['user', 'expires_at'], name='moments_mom_user_id_cb0aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='momentmediadownloadtoken',
            index=models.Index(fields=['couple', 'expires_at'], name='moments_mom_couple__836c18_idx'),
        ),
        migrations.AddIndex(
            model_name='momenttopiclink',
            index=models.Index(fields=['moment', 'created_at'], name='moments_mom_moment__d5fdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='momenttopiclink',
            index=models.Index(fields=['couple', 'created_at'], name='moments_mom_couple__67892e_idx'),
        ),
        migrations.AddConstraint(
            model_name='momenttopiclink',
            constraint=models.UniqueConstraint(fields=('moment', 'topic'), name='unique_moment_builtin_topic_link'),
        ),
        migrations.AddConstraint(
            model_name='momenttopiclink',
            constraint=models.UniqueConstraint(fields=('moment', 'custom_topic'), name='unique_moment_custom_topic_link'),
        ),
    ]
