# Generated by Django 5.0.4 on 2026-08-07 21:22

import apps.moments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentmedia',
            name='file',
            field=models.ImageField(max_length=500, upload_to=apps.moments.models.moment_media_upload_path),
        ),
        migrations.AlterField(
            model_name='momentmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.moments.models.moment_thumbnail_upload_path),
        ),
    ]
