# Generated by Django 5.0.4 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0005_seed_follow_up_prompt'),
        ('couples', '0002_entitlement'),
        ('responses', '0002_topicanalysisjob_topicsyncevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('safety_blocked', 'Safety blocked')], max_length=32)),
                ('topic_stable_key', models.CharField(max_length=160)),
                ('topic_version', models.PositiveSmallIntegerField()),
                ('active_member_ids', models.JSONField(blank=True, default=list)),
                ('deterministic_similarity_score', models.PositiveSmallIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_runs', to='ai.aianalysisresult')),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_runs', to='responses.topicanalysisjob')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='couples.couple')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='responses.topicsession')),
            ],
        ),
        migrations.CreateModel(
            name='AlignmentDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=160)),
                ('score', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_dimensions', to='analysis.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationStarter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_starters', to='analysis.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_text', models.TextField()),
                ('source', models.CharField(default='topic_analysis', max_length=80)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('dismissed', 'Dismissed'), ('converted', 'Converted')], default='proposed', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_clauses', to='analysis.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('alignment_score', models.PositiveSmallIntegerField()),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('common_ground', models.JSONField(blank=True, default=list)),
                ('differences', models.JSONField(blank=True, default=list)),
                ('sensitive_areas', models.JSONField(blank=True, default=list)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_analysis', to='analysis.analysisrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['session', 'version'], name='analysis_an_session_fb70e8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='analysis_an_couple__22ca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['analysis_job', 'created_at'], name='analysis_an_analysi_68f108_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='unique_analysis_run_version_per_session'),
        ),
        migrations.AddIndex(
            model_name='alignmentdimension',
            index=models.Index(fields=['run', 'sort_order'], name='analysis_al_run_id_851cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationstarter',
            index=models.Index(fields=['run', 'sort_order'], name='analysis_co_run_id_d53edd_idx'),
        ),
        migrations.AddIndex(
            model_name='proposedclause',
            index=models.Index(fields=['run', 'sort_order'], name='analysis_pr_run_id_c854d4_idx'),
        ),
        migrations.AddIndex(
            model_name='proposedclause',
            index=models.Index(fields=['status', 'created_at'], name='analysis_pr_status_759654_idx'),
        ),
        migrations.AddIndex(
            model_name='topicanalysis',
            index=models.Index(fields=['alignment_score', 'created_at'], name='analysis_to_alignme_7ca62c_idx'),
        ),
    ]
