# Generated by Django 5.0.4 on 2026-08-07 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('single_choice_with_text', 'Single choice with text'), ('text', 'Text')], default='single_choice_with_text', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic__sort_order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='topics.question')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOptionTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='topics.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=12)),
                ('prompt', models.TextField()),
                ('open_text_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='topics.question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('stable_key', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='topics_topi_is_acti_147b76_idx'), models.Index(fields=['stable_key', 'version'], name='topics_topi_stable__9c64ce_idx')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='topics.topic'),
        ),
        migrations.CreateModel(
            name='TopicTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='topics.topic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'stable_key'), name='unique_question_option_key'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'sort_order'), name='unique_question_option_order'),
        ),
        migrations.AddIndex(
            model_name='questionoptiontranslation',
            index=models.Index(fields=['language'], name='topics_ques_languag_1967b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionoptiontranslation',
            constraint=models.UniqueConstraint(fields=('option', 'language'), name='unique_question_option_translation_language'),
        ),
        migrations.AddIndex(
            model_name='questiontranslation',
            index=models.Index(fields=['language'], name='topics_ques_languag_43993c_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontranslation',
            constraint=models.UniqueConstraint(fields=('question', 'language'), name='unique_question_translation_language'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_active', 'sort_order'], name='topics_ques_topic_i_478293_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['stable_key', 'version'], name='topics_ques_stable__390513_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('topic', 'stable_key', 'version'), name='unique_question_version'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('topic', 'sort_order', 'version'), name='unique_question_order_per_version'),
        ),
        migrations.AddIndex(
            model_name='topictranslation',
            index=models.Index(fields=['language', 'title'], name='topics_topi_languag_ae04ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='topictranslation',
            constraint=models.UniqueConstraint(fields=('topic', 'language'), name='unique_topic_translation_language'),
        ),
    ]
