# Generated by Django 5.0.4 on 2026-08-07 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_entitlement'),
        ('topics', '0002_seed_builtin_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=160)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_topics', to='couples.couple')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_custom_topics', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='topics.coupletopic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('single_choice_with_text', 'Single choice with text'), ('text', 'Text')], default='single_choice_with_text', max_length=40)),
                ('prompt', models.TextField()),
                ('open_text_prompt', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.coupletopic')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='topics.customquestion')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='coupletopic',
            index=models.Index(fields=['couple', 'is_active'], name='topics_coup_couple__1320ed_idx'),
        ),
        migrations.AddIndex(
            model_name='coupletopic',
            index=models.Index(fields=['stable_key', 'version'], name='topics_coup_stable__e36b9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupletopic',
            constraint=models.UniqueConstraint(fields=('couple', 'stable_key', 'version'), name='unique_couple_topic_version'),
        ),
        migrations.AddIndex(
            model_name='customquestion',
            index=models.Index(fields=['topic', 'is_active', 'sort_order'], name='topics_cust_topic_i_ff3143_idx'),
        ),
        migrations.AddIndex(
            model_name='customquestion',
            index=models.Index(fields=['stable_key', 'version'], name='topics_cust_stable__722a09_idx'),
        ),
        migrations.AddConstraint(
            model_name='customquestion',
            constraint=models.UniqueConstraint(fields=('topic', 'stable_key', 'version'), name='unique_custom_question_version'),
        ),
        migrations.AddConstraint(
            model_name='customquestion',
            constraint=models.UniqueConstraint(fields=('topic', 'sort_order', 'version'), name='unique_custom_question_order_version'),
        ),
        migrations.AddConstraint(
            model_name='customquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'stable_key'), name='unique_custom_question_option_key'),
        ),
        migrations.AddConstraint(
            model_name='customquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'sort_order'), name='unique_custom_question_option_order'),
        ),
    ]
