# Generated by Django 5.0.4 on 2026-08-07 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('longest_count', models.PositiveIntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.SlugField(max_length=120, unique=True)),
                ('prompt', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'stable_key'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='daily_daily_is_acti_1a0fab_idx'), models.Index(fields=['category', 'sort_order'], name='daily_daily_categor_111f6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_date', models.DateField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('revealed', 'Revealed')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='couples.couple')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='daily.dailyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReveal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revealed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reveal', to='daily.dailyassignment')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reveals', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField()),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_answers', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_answers', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='daily.dailyassignment')),
            ],
            options={
                'indexes': [models.Index(fields=['assignment', 'user'], name='daily_daily_assignm_f9f5aa_idx'), models.Index(fields=['couple', 'answered_at'], name='daily_daily_couple__b4a020_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyanswer',
            constraint=models.UniqueConstraint(fields=('assignment', 'user'), name='unique_daily_answer_per_user_assignment'),
        ),
        migrations.AddIndex(
            model_name='dailyassignment',
            index=models.Index(fields=['couple', 'local_date'], name='daily_daily_couple__41ccaa_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyassignment',
            index=models.Index(fields=['status', 'local_date'], name='daily_daily_status_0cefc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyassignment',
            constraint=models.UniqueConstraint(fields=('couple', 'local_date'), name='unique_daily_assignment_per_couple_date'),
        ),
        migrations.AddIndex(
            model_name='dailyreveal',
            index=models.Index(fields=['couple', 'revealed_at'], name='daily_daily_couple__c58b01_idx'),
        ),
    ]
