# Generated by Django 5.0.4 on 2026-08-07 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('couples', '0002_entitlement'),
        ('responses', '0002_topicanalysisjob_topicsyncevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived')], default='open', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_threads', to='analysis.analysisrun')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='couples.couple')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_discussion_threads', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='responses.topicsession')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_messages', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='couples.couple')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussions.discussionthread')),
            ],
        ),
        migrations.CreateModel(
            name='MediationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('context_message_count', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_requests', to='couples.couple')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediation_requests', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_requests', to='discussions.discussionthread')),
            ],
        ),
        migrations.CreateModel(
            name='MediationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('model', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_responses', to='couples.couple')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediation_response', to='discussions.discussionmessage')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='discussions.mediationrequest')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_responses', to='discussions.discussionthread')),
            ],
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='discussions_couple__dffb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['session', 'created_at'], name='discussions_session_ff5e65_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['analysis_run', 'created_at'], name='discussions_analysi_89ef03_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionmessage',
            index=models.Index(fields=['thread', 'created_at'], name='discussions_thread__07a1be_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionmessage',
            index=models.Index(fields=['couple', 'created_at'], name='discussions_couple__4f3f11_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionmessage',
            index=models.Index(fields=['sender_type', 'created_at'], name='discussions_sender__a4e502_idx'),
        ),
        migrations.AddIndex(
            model_name='mediationrequest',
            index=models.Index(fields=['thread', 'status', 'created_at'], name='discussions_thread__dfde27_idx'),
        ),
        migrations.AddIndex(
            model_name='mediationrequest',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='discussions_couple__72c339_idx'),
        ),
        migrations.AddIndex(
            model_name='mediationresponse',
            index=models.Index(fields=['thread', 'created_at'], name='discussions_thread__a8c639_idx'),
        ),
    ]
