# Generated by Django 5.0.4 on 2026-08-07 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(choices=[('curated', 'Curated'), ('fallback', 'Fallback'), ('ai_suggested', 'AI suggested')], default='curated', max_length=32)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('safety_policy_version', models.CharField(default='challenge_policy_v1', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'stable_key'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='challenges__is_acti_9a5434_idx'), models.Index(fields=['source', 'is_active'], name='challenges__source_e84aec_idx'), models.Index(fields=['category', 'sort_order'], name='challenges__categor_4edcf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('curated', 'Curated'), ('fallback', 'Fallback'), ('ai_suggested', 'AI suggested')], default='curated', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('starts_on', models.DateField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('suggested_payload', models.JSONField(blank=True, default=dict)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('fallback_reason', models.CharField(blank=True, max_length=160)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_challenges', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='challenges.challenge')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_assignments', to='couples.couple')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeMemberCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_completions', to='challenges.challengeassignment')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='challengeassignment',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='challenges__couple__45f7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeassignment',
            index=models.Index(fields=['source', 'created_at'], name='challenges__source_696d89_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeassignment',
            index=models.Index(fields=['starts_on', 'due_on'], name='challenges__starts__83a8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='challengemembercompletion',
            index=models.Index(fields=['assignment', 'user'], name='challenges__assignm_364374_idx'),
        ),
        migrations.AddIndex(
            model_name='challengemembercompletion',
            index=models.Index(fields=['couple', 'completed_at'], name='challenges__couple__ffab6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengemembercompletion',
            constraint=models.UniqueConstraint(fields=('assignment', 'user'), name='unique_challenge_completion_per_assignment_user'),
        ),
    ]
