# Generated by Django 5.0.4 on 2026-08-07 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0002_topicanalysisjob_topicsyncevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Refused'), ('failed', 'Failed'), ('invalid_output', 'Invalid output')], max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(default='topic_analysis', max_length=120)),
                ('output', models.JSONField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('refusal_reason', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='responses.topicanalysisjob')),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('version', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('system_prompt', models.TextField()),
                ('developer_prompt', models.TextField(blank=True)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'is_active'], name='ai_aiprompt_key_7a639e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aipromptversion',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='unique_ai_prompt_key_version'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='prompt_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_results', to='ai.aipromptversion'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['status', 'created_at'], name='ai_aianalys_status_6af9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['model', 'created_at'], name='ai_aianalys_model_db14fd_idx'),
        ),
    ]
