# Generated by Django 5.0.4 on 2026-08-07 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_seed_topic_analysis_prompt'),
        ('responses', '0002_topicanalysisjob_topicsyncevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisresult',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Refused'), ('failed', 'Failed'), ('invalid_output', 'Invalid output'), ('safety_blocked', 'Safety blocked')], max_length=32),
        ),
        migrations.CreateModel(
            name='AISafetyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=20)),
                ('category', models.CharField(choices=[('abuse_coercion', 'Abuse or coercion'), ('self_harm', 'Self-harm'), ('threat', 'Threat'), ('sexual_content', 'Sexual content'), ('minors', 'Minors'), ('medical_legal', 'Medical or legal'), ('prompt_injection', 'Prompt injection')], max_length=64)),
                ('severity', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('high', 'High'), ('blocked', 'Blocked')], max_length=20)),
                ('route', models.CharField(choices=[('normal', 'Normal AI task'), ('restricted_safety', 'Restricted safety response'), ('blocked', 'Blocked')], max_length=32)),
                ('detector', models.CharField(default='local_policy_v1', max_length=80)),
                ('content_fingerprint', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_events', to='responses.topicanalysisjob')),
            ],
            options={
                'indexes': [models.Index(fields=['analysis_job', 'stage'], name='ai_aisafety_analysi_ae2e58_idx'), models.Index(fields=['category', 'severity', 'created_at'], name='ai_aisafety_categor_94641d_idx'), models.Index(fields=['route', 'created_at'], name='ai_aisafety_route_2ecf15_idx')],
            },
        ),
    ]
