# Generated by Django 5.0.4 on 2026-08-07 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aianalysisresult_status_aisafetyevent'),
        ('couples', '0002_entitlement'),
        ('responses', '0002_topicanalysisjob_topicsyncevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFollowUpQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('refused', 'Refused'), ('failed', 'Failed'), ('invalid_output', 'Invalid output'), ('safety_blocked', 'Safety blocked')], max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('topic_stable_key', models.CharField(max_length=160)),
                ('topic_version', models.PositiveSmallIntegerField()),
                ('follow_up_question', models.TextField(blank=True)),
                ('internal_reason', models.TextField(blank=True)),
                ('skip', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('refusal_reason', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_follow_ups', to='couples.couple')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_questions', to='ai.aipromptversion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_follow_ups', to='responses.topicsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'user'], name='ai_aifollow_session_975e18_idx'), models.Index(fields=['status', 'created_at'], name='ai_aifollow_status_36e103_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aifollowupquestion',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_ai_follow_up_per_session_user'),
        ),
    ]
