# Generated by Django 5.0.4 on 2026-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='billing_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='couple_action',
            field=models.CharField(choices=[('none', 'None'), ('archived', 'Archived'), ('dissolved', 'Dissolved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='partner_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='sessions_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataexportrequest',
            name='byte_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataexportrequest',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dataexportrequest',
            name='export_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
