# Generated by Django 5.0.4 on 2026-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_features', '0002_accountdeletionrequest_billing_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='couple_action',
            field=models.CharField(choices=[('none', 'None'), ('archived', 'Archived'), ('dissolved', 'Dissolved'), ('deleted', 'Deleted')], default='none', max_length=20),
        ),
    ]
