# Generated by Django 5.0.4 on 2026-08-07 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0005_seed_follow_up_prompt'),
        ('couples', '0002_entitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('collecting', 'Collecting perspectives'), ('perspectives_locked', 'Perspectives locked'), ('bridge_ready', 'Bridge ready'), ('discussion_open', 'Discussion open'), ('resolved', 'Resolved')], default='collecting', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_threads', to='couples.couple')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_conflict_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('proposed_pact_changes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_resolutions', to='couples.couple')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_resolutions', to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='conflicts.conflictthread')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictPerspective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('situation', models.TextField()),
                ('feelings', models.TextField(blank=True)),
                ('needs', models.TextField(blank=True)),
                ('requested_outcome', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_perspectives', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_perspectives', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='conflicts.conflictthread')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('render_as', models.CharField(default='text', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_messages', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_messages', to='couples.couple')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conflicts.conflictthread')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictMediation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_mediations', to='couples.couple')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_mediations', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediations', to='conflicts.conflictthread')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictBridge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Refused'), ('failed', 'Failed'), ('invalid_output', 'Invalid output'), ('safety_blocked', 'Safety blocked'), ('policy_blocked', 'Policy blocked')], max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('neutral_summary', models.TextField(blank=True)),
                ('common_ground', models.JSONField(blank=True, default=list)),
                ('partner_summaries', models.JSONField(blank=True, default=dict)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('refusal_reason', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_bridges', to='couples.couple')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflict_bridges', to='ai.aipromptversion')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bridge', to='conflicts.conflictthread')),
            ],
        ),
        migrations.AddIndex(
            model_name='conflictthread',
            index=models.Index(fields=['couple', 'status', 'created_at'], name='conflicts_c_couple__e8012b_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['couple', 'created_at'], name='conflicts_c_couple__62b6be_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictperspective',
            index=models.Index(fields=['thread', 'user'], name='conflicts_c_thread__2bc3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictperspective',
            index=models.Index(fields=['couple', 'locked_at'], name='conflicts_c_couple__ad58fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='conflictperspective',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_conflict_perspective_per_thread_user'),
        ),
        migrations.AddIndex(
            model_name='conflictmessage',
            index=models.Index(fields=['thread', 'created_at'], name='conflicts_c_thread__d74438_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictmessage',
            index=models.Index(fields=['couple', 'created_at'], name='conflicts_c_couple__d51795_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictbridge',
            index=models.Index(fields=['status', 'created_at'], name='conflicts_c_status_91934c_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictbridge',
            index=models.Index(fields=['couple', 'created_at'], name='conflicts_c_couple__fc8476_idx'),
        ),
    ]
