# Generated by Django 5.0.4 on 2026-08-07 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0005_seed_follow_up_prompt'),
        ('couples', '0002_entitlement'),
        ('daily', '0002_seed_daily_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('input_start_date', models.DateField()),
                ('input_end_date', models.DateField()),
                ('minimum_revealed_days', models.PositiveSmallIntegerField(default=3)),
                ('revealed_day_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ineligible', 'Ineligible'), ('succeeded', 'Succeeded'), ('refused', 'Refused'), ('failed', 'Failed'), ('invalid_output', 'Invalid output'), ('safety_blocked', 'Safety blocked')], default='queued', max_length=32)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('provider_response_id', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(default='monthly_insight', max_length=120)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('refusal_reason', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_insights', to='couples.couple')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_insights', to='ai.aipromptversion')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyInsightInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_date', models.DateField()),
                ('question_stable_key', models.CharField(max_length=120)),
                ('question_prompt', models.TextField()),
                ('text_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_insight_inputs', to='daily.dailyanswer')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_insight_inputs', to='daily.dailyassignment')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='insights.monthlyinsight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_insight_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='monthlyinsight',
            index=models.Index(fields=['couple', 'year', 'month'], name='insights_mo_couple__ba4652_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyinsight',
            index=models.Index(fields=['status', 'queued_at'], name='insights_mo_status_d14b75_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinsight',
            constraint=models.UniqueConstraint(fields=('couple', 'year', 'month'), name='unique_monthly_insight_per_couple_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinsight',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_insight_month_range'),
        ),
        migrations.AddIndex(
            model_name='monthlyinsightinput',
            index=models.Index(fields=['insight', 'local_date'], name='insights_mo_insight_4fa054_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyinsightinput',
            index=models.Index(fields=['assignment', 'user'], name='insights_mo_assignm_9416c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinsightinput',
            constraint=models.UniqueConstraint(fields=('insight', 'answer'), name='unique_monthly_insight_input_answer'),
        ),
    ]
