# Generated by Django 5.0.4 on 2026-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('partner_invitation', 'Partner invitation'), ('partner_joined', 'Partner joined'), ('topic_completed', 'Topic completed'), ('analysis_ready', 'Analysis ready'), ('pact_approval_required', 'Pact approval required'), ('pact_activated', 'Pact activated'), ('account_deletion_requested', 'Account deletion requested')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('partner_invitation', 'Partner invitation'), ('partner_joined', 'Partner joined'), ('topic_completed', 'Topic completed'), ('analysis_ready', 'Analysis ready'), ('pact_approval_required', 'Pact approval required'), ('pact_activated', 'Pact activated'), ('account_deletion_requested', 'Account deletion requested')], max_length=64),
        ),
    ]
